require 'rabatt/providers/base'
require 'rabatt/providers/adtraction'
require 'rabatt/providers/double'
require 'rabatt/providers/adrecord'
require 'rabatt/providers/tradedoubler'
require 'rabatt/providers/zanox'
require 'rabatt/providers/tradetracker'
require 'rabatt/providers/webgains'
